ktor:
  application:
    modules:
      - ru.fanofstars.ApplicationKt.module
  deployment:
    port: 8080
    host: 0.0.0.0
postgres:
  url: "jdbc:postgresql://localhost:5432/closetdb"
  user: "myuser"
  password: "mypassword"
  jwt: asdfghjk
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
